name: Upload via FTP

on:
  push:
    branches:
      - main  
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Upload tpa.html via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: "/path/to/your/server/directory/"
        local-dir: "./"   # This is the default, means root of your repository
        exclude: "*"      # Exclude everything
        include: "tpa.html"  # Include only tpa.html
